apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  labels:
    app: {{SERVICE_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app: {{SERVICE_NAME}}
    spec:
      containers:
      - name: {{SERVICE_NAME}}
        image: my-registry/{{SERVICE_NAME}}:latest
        ports:
        - containerPort: {{SERVICE_PORT}} # Ganti jadi 8001-8010 sesuai jatah
        env:
        - name: DB_HOST
          value: "db-postgres-service"
        - name: DB_NAME
          value: "db_{{SERVICE_NAME}}" # Contoh: db_order
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"