pipeline {
    agent any

    tools {
        go 'go-1.21' 
    }

    // --- GANTI SERVICE_NAME SESUAI FOLDERNYA ---
    environment {
        SERVICE_NAME = "location-service"
        DOCKER_IMAGE = "drikz/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        // 1. Checkout
        stage('1. Checkout Repo') {
            steps { checkout scm }
        }

        // 2. Unit Tests
        stage('2. Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go test -v ./... -skip Functional' 
                }
            }
        }

        // 3. Lint/Vet
        stage('3. Lint/Vet') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go vet ./...'
                }
            }
        }

        // 4. Build & Push
        stage('4. Build & Push Image') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-login', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        // 5. Functional Tests
        stage('5. Functional Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go test -v -run Functional ./... || exit 0'
                }
            }
        }

        // 6. Deploy & Verify
        stage('6. Deploy & Verify K8s') {
            steps {
                dir("${SERVICE_NAME}") {
                    // Update image tag
                    sh "sed -i 's|my-registry/${SERVICE_NAME}:latest|${DOCKER_IMAGE}|g' k8s/deployment.yaml"
                    
                    withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG_TMP')]) {
                        // Trik Jalur Suci
                        sh 'cp $KUBECONFIG_TMP ./kubeconfig_local'
                        sh 'sed -i "s|127.0.0.1|host.docker.internal|g" ./kubeconfig_local'
                        
                        // Eksekusi Apply & Rollout (Bypass TLS)
                        sh "kubectl --kubeconfig=./kubeconfig_local apply -f k8s/ --validate=false --insecure-skip-tls-verify=true"
                        sh "kubectl --kubeconfig=./kubeconfig_local rollout status deployment/${SERVICE_NAME} --timeout=90s --insecure-skip-tls-verify=true"
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline untuk ${SERVICE_NAME} selesai dieksekusi."
        }
    }
}