pipeline {
    agent any
    
    stages {
        // Tahap build & push docker biasanya dilewati karena memakai image dari ACR milik Mudrik
        
        stage('Deploy Location Service to AKS') {
            steps {
                // Memastikan Jenkins mengeksekusi manifes location-service yang baru di-update Mudrik
                sh 'kubectl apply -f location-service/deployment.yaml'
            }
        }
    }
}