apiVersion: v1
kind: Service

metadata:
  name: merchant-service

spec:
  selector:
    app: merchant-service

  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089

  type: NodePort
