apiVersion: v1
kind: Service

metadata:
  name: merchant-service

spec:
  selector:
    app: merchant-service

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

  type: NodePort