// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	model "shop-order-service/model"

	gomock "github.com/golang/mock/gomock"
)

// MockShopOrderRepository is a mock of ShopOrderRepository interface.
type MockShopOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopOrderRepositoryMockRecorder
}

// MockShopOrderRepositoryMockRecorder is the mock recorder for MockShopOrderRepository.
type MockShopOrderRepositoryMockRecorder struct {
	mock *MockShopOrderRepository
}

// NewMockShopOrderRepository creates a new mock instance.
func NewMockShopOrderRepository(ctrl *gomock.Controller) *MockShopOrderRepository {
	mock := &MockShopOrderRepository{ctrl: ctrl}
	mock.recorder = &MockShopOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopOrderRepository) EXPECT() *MockShopOrderRepositoryMockRecorder {
	return m.recorder
}

// SaveCart mocks base method.
func (m *MockShopOrderRepository) SaveCart(cart *model.ShoppingCart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCart", cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCart indicates an expected call of SaveCart.
func (mr *MockShopOrderRepositoryMockRecorder) SaveCart(cart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCart", reflect.TypeOf((*MockShopOrderRepository)(nil).SaveCart), cart)
}
