pipeline {
    agent any

    environment {
        SERVICE_NAME = "dispatch-service"
        // Akun Docker Hub lu tetep drikz
        DOCKER_IMAGE = "drikz/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    // Pake sh karena Jenkins lu Linux
                    sh 'GOWORK=off go test -v ./... -skip Functional' 
                }
            }
        }

        stage('3. Lint/Vet') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'GOWORK=off go vet ./...'
                }
            }
        }

        stage('4. Build & Push Image') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-login', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        // Di Linux, panggil variabel pake $ dan gunakan single quote agar aman dari injection
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        stage('5. Functional Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    // Berjalan lancar pake mock database
                    sh 'GOWORK=off go test -v -run Functional ./... || exit 0'
                }
            }
        }

        stage('6. Deploy & Verify K8s') {
            steps {
                dir("${SERVICE_NAME}") {
                    // Pake 'sed' bawaan Linux untuk replace teks registry di k8s/deployment.yaml
                    sh "sed -i 's|my-registry/${SERVICE_NAME}:latest|${DOCKER_IMAGE}|g' k8s/deployment.yaml"
                    
                    // Karena Jenkins lu di Linux Container, kita bypass atau arahkan ke config internal container
                    sh 'mkdir -p ~/.kube'
                    sh 'kubectl apply -f k8s/ --validate=false'
                    sh 'kubectl rollout status deployment/dispatch-service --timeout=90s'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline untuk ${SERVICE_NAME} selesai dieksekusi."
        }
    }
}