pipeline {
    agent any

    environment {
        SERVICE_NAME = "dispatch-service"
        // FIXED: Menggunakan akun Docker Hub lu (drikz)
        DOCKER_IMAGE = "drikz/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat 'go test -v ./... -skip Functional' 
                }
            }
        }

        stage('3. Lint/Vet') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat 'go vet ./...'
                }
            }
        }

        stage('4. Build & Push Image') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat "docker build -t ${DOCKER_IMAGE} ."
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-login', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        bat "echo %DOCKER_PASS%| docker login -u %DOCKER_USER% --password-stdin"
                        bat "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        stage('5. Functional Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat 'go test -v -run Functional ./... || exit 0'
                }
            }
        }

        stage('6. Deploy & Verify K8s') {
            steps {
                dir("${SERVICE_NAME}") {
                    powershell "((Get-Content k8s/deployment.yaml) -replace 'my-registry/${SERVICE_NAME}:latest', '${DOCKER_IMAGE}') | Set-Content k8s/deployment.yaml"
                    
                    // FIXED: Path Windows tetep pake ASUS sesuai kata lu!
                    bat 'kubectl --kubeconfig="C:\\Users\\ASUS\\.kube\\config" apply -f k8s/'
                    bat 'kubectl --kubeconfig="C:\\Users\\ASUS\\.kube\\config" rollout status deployment/dispatch-service --timeout=90s'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline untuk ${SERVICE_NAME} selesai dieksekusi."
        }
    }
}