pipeline {
    agent any

    environment {
        SERVICE_NAME = "translog-service"
        DOCKER_IMAGE = "kuroissaint/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'go test -v ./... -skip Functional' 
                }
            }
        }

        stage('3. Build & Push Image') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        stage('4. Functional Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh 'go test -v -run Functional ./...'
                }
            }
        }

        stage('5. Deploy & Verify K8s') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "sed -i 's|my-registry/${SERVICE_NAME}:latest|${DOCKER_IMAGE}|g' k8s/deployment.yaml"
                    sh "kubectl apply -f k8s/"
                    sh "kubectl rollout status deployment/${SERVICE_NAME} --timeout=90s"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline untuk ${SERVICE_NAME} selesai dieksekusi."
        }
    }
}