// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	reviewrating "github.com/kuroissaint/tubes2dpcc/reviewrating-service"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// SaveReview mocks base method.
func (m *MockReviewRepository) SaveReview(ctx context.Context, review reviewrating.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveReview", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveReview indicates an expected call of SaveReview.
func (mr *MockReviewRepositoryMockRecorder) SaveReview(ctx, review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveReview", reflect.TypeOf((*MockReviewRepository)(nil).SaveReview), ctx, review)
}
