apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch-service
  template:
    metadata:
      labels:
        app: dispatch-service
    spec:
      imagePullSecrets:
      - name: kuncimudrik # <-- BIAR AKS TEMENMU BISA TEMBUS ACR LU
      containers:
      - name: dispatch-service
        image: ojektubesregistry.azurecr.io/dispatch-service:v100
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        env:
        - name: SERVICE_PORT
          value: "8003"
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017"
        - name: LOCATION_SERVICE_URL
          value: "http://location-service-service:8002" # <-- DIREDIREKSI KE ALAMAT LOCATION YANG BENAR
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch-service-service
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: dispatch-service