apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch-service
  template:
    metadata:
      labels:
        app: dispatch-service
    spec:
      containers:
      - name: dispatch-service
        image: acktubes.azurecr.io/dispatch-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: SERVICE_PORT
          value: "8003"
        - name: LOCATION_SERVICE_URL
          value: "http://location-service-cluster:8002"
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch-service-public
spec:
  # LoadBalancer akan memerintahkan Azure untuk otomatis membuat 1 buah IP Publik berbayar
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 8003
  selector:
    app: dispatch-service