apiVersion: v1
kind: Service
metadata:
  name: dispatch-service-service
spec:
  selector:
    app: dispatch-service
  ports:
    - protocol: TCP
      port: 8003      # Port luar
      targetPort: 8003 # Port dalam container
  type: ClusterIP