apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: finance-service
          image: pricingfinance.azurecr.io/finance-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "postgres://kantin_admin:kantin123@postgres-service:5432/postgres?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  type: ClusterIP
  selector:
    app: finance-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080