pipeline {
    agent any

    stages {
        // Poin 1: Checkout Repo
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        // Poin 2: Unit Tests
        stage('2. Unit Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    echo 'Running Unit Tests for Finance Service...'
                    sh 'go test -v ./...'
                }
            }
        }

        // Poin 3: Lint/Vet
        stage('3. Lint/Vet') {
            steps {
                sh 'go vet ./...'
            }
        }

        // Poin 4: Build Image (Lokal)
        stage('4. Build Image') {
            steps {
                sh 'docker build -t finance-service:latest .'
            }
        }

        // Poin 5: Functional Tests
        stage('5. Functional Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    echo 'Running Functional Tests for Finance Service...'
                    sh 'go test -v -tags=functional ./...'
                }
            }
        }

        // Poin 6: Push Image (Skip)
        stage('6. Push Image') {
            steps {
                echo 'Push image skipped (Menggunakan image lokal)'
            }
        }

        // Poin 7: Deploy di Kubernetes
        stage('7. Deploy di Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/finance-deploy.yaml'
            }
        }

        // Poin 8: Verify
        stage('8. Verify') {
            steps {
                echo 'Verifying deployment status...'
            }
        }
    }
}