pipeline {
    agent any

    environment {
        SERVICE_NAME = "pricing-service"
        DOCKER_IMAGE = "kelcloud23/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Go Validation (Test & Vet)') {
            steps {
                dir('pricing-service') {
                    bat '''
                        set GOWORK=off
                        go vet ./...
                        go test ./... -v
                    '''
                }
            }
        }

        stage('3. Build Image') {
            steps {
                dir('pricing-service') {
                    bat "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('4. Push Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-login', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    bat '''
                        echo %DOCKER_PASS%| docker login -u %DOCKER_USER% --password-stdin
                        docker push ''' + DOCKER_IMAGE
                }
            }
        }

        stage('5. Deploy & Verify Kubernetes') {
            steps {
                dir('pricing-service') {
                    withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG_TMP')]) {
                        bat """
                            kubectl --kubeconfig="%KUBECONFIG_TMP%" apply -f k8s/
                            kubectl --kubeconfig="%KUBECONFIG_TMP%" set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${DOCKER_IMAGE}
                            kubectl --kubeconfig="%KUBECONFIG_TMP%" rollout status deployment/${SERVICE_NAME} --timeout=60s || exit 0
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Successfully deployed ${SERVICE_NAME} version ${env.BUILD_NUMBER}"
        }
        failure {
            echo "Deployment failed! Check logs."
        }
    }
}