apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-order-service
  labels:
    app: shop-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-order-service
  template:
    metadata:
      labels:
        app: shop-order-service
    spec:
      containers:
      - name: shop-order-service
        image: kelcloud23/shop-order-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL