apiVersion: v1
kind: Service
metadata:
  name: shop-order-service
spec:
  selector:
    app: shop-order-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer