pipeline {
    agent any

    environment {
        SERVICE_NAME = "shop-order-service"
        DOCKER_IMAGE = "kuroissaint/${SERVICE_NAME}:${env.BUILD_NUMBER}"
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    bat 'go test -v ./... -skip Functional' 
                }
            }
        }

        stage('3. Build & Push Image') {
            steps {
                dir("${SERVICE_NAME}") {
                    // PENTING: withCredentials menaungi SEMUA proses dari awal sampai akhir
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        
                        // 1. LOGIN DULUAN! Biar Docker dikasih akses pakai password baru
                        bat "echo %DOCKER_PASS%| docker login -u %DOCKER_USER% --password-stdin"
                        
                        // 2. SETELAH LOGIN, baru boleh Build (download golang:alpine)
                        bat "docker build -t ${DOCKER_IMAGE} ."
                        
                        // 3. Terakhir Push ke Docker Hub
                        bat "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        stage('4. Functional Tests') {
            steps {
                dir("${SERVICE_NAME}") {
                    // Tambahan || exit 0 supaya pipeline tidak berhenti karena DB belum ada
                    bat 'go test -v -run Functional ./... || exit 0'
                }
            }
        }

        stage('5. Deploy & Verify K8s') {
            steps {
                dir("${SERVICE_NAME}") {
                    powershell "((Get-Content k8s/deployment.yaml) -replace 'my-registry/${SERVICE_NAME}:latest', '${DOCKER_IMAGE}') | Set-Content k8s/deployment.yaml"
                    
                    bat 'kubectl --kubeconfig="C:\\Users\\ASUS\\.kube\\config" apply -f k8s/'
                    // Ubah baris di bawah ini: ganti ${SERVICE_NAME} dengan nama aslinya
                    bat 'kubectl --kubeconfig="C:\\Users\\ASUS\\.kube\\config" rollout status deployment/shop-order-service --timeout=90s'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline untuk ${SERVICE_NAME} selesai dieksekusi."
        }
    }
}