pipeline {
    agent any

    environment {
        SERVICE_NAME = "shop-order-service"
        DOCKER_IMAGE = "kelcloud23/${SERVICE_NAME}:${env.BUILD_NUMBER}"
        GOWORK = 'off'
    }

    stages {
        stage('1. Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir('shop-order-service') {
                    bat 'go test ./... -v'
                }
            }
        }

        stage('3. Lint / Vet') {
            steps {
                dir('shop-order-service') {
                    bat 'go vet ./...'
                }
            }
        }

        stage('4. Build Image (Lokal)') {
            steps {
                dir('shop-order-service') {
                    bat "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('5. Functional Tests') {
            steps {
                dir('shop-order-service') {
                    bat 'go test -tags=functional ./... -v'
                }
            }
        }

        stage('6. Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-login', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    bat 'docker login -u %DOCKER_USER% -p %DOCKER_PASS%'
                    bat "docker push ${DOCKER_IMAGE}"
                }
            }
        }

        stage('7. Deploy di Kubernetes') {
            steps {
                dir('shop-order-service') {
                    withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG_TMP')]) {
                        bat 'kubectl --kubeconfig="%KUBECONFIG_TMP%" apply -f k8s/'
                    }
                }
            }
        }

        stage('8. Verify') {
            steps {
                dir('shop-order-service') {
                    withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG_TMP')]) {
                        bat "kubectl --kubeconfig=\"%KUBECONFIG_TMP%\" rollout status deployment/${SERVICE_NAME} --timeout=90s || exit 0"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Successfully deployed ${SERVICE_NAME} version ${env.BUILD_NUMBER}"
        }
        failure {
            echo "Deployment failed! Check logs."
        }
    }
}