apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: ojektubesregistry.azurecr.io/gateway-service:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kuncimudrik
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-public
spec:
  type: LoadBalancer        # <--- Cuma Gateway yang boleh punya IP Publik
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gateway-service
    