apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      imagePullSecrets:
      - name: kuncimudrik
      containers:
      - name: location-service
        image: ojektubesregistry.azurecr.io/location-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        env:
        - name: SERVICE_PORT
          value: "8002"
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: location-service-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: location-service