apiVersion: v1
kind: Service
metadata:
  name: location-service-service
spec:
  selector:
    app: location-service
  ports:
    - protocol: TCP
      port: 8002      # Port yang diakses dari luar
      targetPort: 8002 # Port di dalam container
  type: ClusterIP